name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Deploy to Vuepress
      uses: jenkey2011/vuepress-deploy@master
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: install && npm run-script docs:build
        BUILD_DIR: docs/.vuepress/dist/
